### ISSUE TITLE
MNIST_M dataset

### ISSUE THREAD

**Issue by andrewyulma** [CuthbertCai/pytorch_DAN#1]
Hi,
I'm trying to reproduce the results of MNIST -> MNIST experiment according to pytorch_DAN provided by you. 
But the MNIST_M dataset is not available at [Yaroslav Ganin's homepage].  I cannot find proper code for generating it or download it. In fact, i have tired some methods to generate this dataset, but it cannot decode. 
I would appreciate it if you could help me and share the MNIST_M dataset you used.
Thank you in advance!

**Comment by CuthbertCai** [comment]
@yulimma I have compressed MNIST_M dataset to a zip file, and uploaded it to MEGA Cloud. You could download it according to the updated README. The `preprocess.py` file should not be used in this situation.

**Comment by andrewyulma** [comment]
Very thanks for your support! It works. This is a big favor.
